### ISSUE TITLE
Getting error: Invalid Request - Error Code 4075

### ISSUE THREAD

**Issue by jtl3d** [sakaruk/shareasale-report#1]
This is a great repo! It looks like it is generating the hash correctly, but I'm getting the error whenever I try any of the reports. I'm passing my affiliate ID, the token and secret key and specifying action (and any required params), but same result every time. Have you run into this?

Does the SHA need to be all upper case?

Any help would be much appreciated.

Also, I think it would be best if the version could be overridden via the $params argument... I can make a pull request if you agree.

**Comment by sakaruk** [comment]
Hello there

What are the codes that you have used to generate the report. You have to only give the authentication data once and the report can be generated easily though passing other parameters like the example below. Seems like you have an authentication problem http://wiki.shareasale.com/2014/09/13/invalid-request-error-code-4075/

```
ShareASale.Report({
  action : 'activity',
  dateStart : '19/06/2017',
  dateEnd : '20/06/2017'
}, function(err,data) {
  console.log(err, data)
})  
```

**Comment by sakaruk** [comment]
You can make a pull request :)

**Comment by jtl3d** [comment]
I still can't get it to work. I think I'm doing everything right, but I keep getting that error. If I change the version to 1.3, I don't get that error because it was before they added the authentication header. Any ideas??

```
const ShareASale = Affiliate({ // eslint-disable-line new-cap
  affiliateId: shareASale.affiliateId,
  token: shareASale.token,
  secretKey: shareASale.secretKey,
});

const getShareASaleTransactions = () => {
  // test
  return new Promise((fulfill, reject) => {
    ShareASale.Report({ // eslint-disable-line new-cap
      action: 'activity',
      dateStart: moment().subtract(90, 'days').format('MM/DD/YYYY'),
    }, (err, data) => {
      if (err) {
        reject(err);
      } else {
        fulfill(data);
      }
    });
  });
};
```

**Comment by jtl3d** [comment]
Oh man, dumb mistake: I did secretKey instead of api_secret. It's working now! Thanks!
